
baseURL                        = 'https://rvspoc.org/'
languageCode                   = 'zh-CN'
title                          = 'RISC-V 软件移植及优化锦标赛'
theme                          = 'ananke'
paginate                       = 100
timeZone                       = "Asia/Shanghai"
pluralizeListTitles            = false
defaultContentLanguage         = 'zh'
defaultContentLanguageInSubdir = false

#
# Uncomment the below configuration if a common/fallback featured image is
# necessary, the image should be copied to the 'static/images/' directory.
#[cascade]
#  featured_image = 'images/<the-name>.jpg'
#

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Although it shows "unsafe", for this project anyone with document
      # editing privileges also has configuration file editing privileges, so
      # just pay more attention to the html code in the markdown. This will help
      # you to customise the style of the article to a greater extent.
      unsafe = true

[params]
  author = ''
  email = 'rvspoc@cyberlimes.cn'
  mainSections = ['posts']
  recent_posts_number = 10
  background_color_class = 'bg-orange'
  custom_css = ["cus_var.scss", "cus_page.scss", "cus_site.scss", "cus_section.scss"]
  body_classes = "sans-serif"
  [[params.ananke_socials]]
    name = 'github'
    url = 'https://github.com/plctlab/rvspoc'

[permalinks]
  [permalinks.page]
    posts = '/:slug/'
    challenges = '/:slug/'
  [permalinks.section]
    posts = '/posts/'
    challenges = '/challenges/'

[languages]
  [languages.zh]
    contentDir = 'content/zh'
    disabled = false
    languageCode = 'zh-CN'
    languageDirection = 'ltr'
    languageName = '简体中文'
    title = 'RISC-V 软件移植及优化锦标赛'
    weight = 1
    hasCJKLanguage = true
    summaryLength = 230
    [languages.zh.params]
      #registration_url = 'https://www.wenjuan.com/s/UZBZJv0BMdV/'
      [[languages.zh.params.banners]]
        text = '本次锦标赛的报名与提交截止日期将延长至 2024 年 2 月 29 日。'
        link = 'https://rvspoc.org/02/'
      [[languages.zh.params.banners]]
        text = '本次锦标赛的获奖结果已公布，公示期为 2024 年 4 月 3 日 —— 2024 年 4 月 10 日。'
        link = 'https://rvspoc.org/05/'
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'RISC-V Software Porting and Optimization Championship'
    weight = 2
    [languages.en.params]
      #registration_url = 'https://www.wenjuan.com/s/UZBZJveQl0k/'
      [[languages.en.params.banners]]
        text = 'The deadline for registrations and submissions for this championship is extended to February 29, 2024.'
        link = 'https://rvspoc.org/02/'
      [[languages.en.params.banners]]
        text = '本次锦标赛的获奖结果已公布，公示期为 2024 年 4 月 3 日 —— 2024 年 4 月 10 日。'
        link = 'https://rvspoc.org/05/'
  [languages.ru]
    contentDir = 'content/ru'
    disabled = false
    languageCode = 'ru-RU'
    languageDirection = 'ltr'
    languageName = 'Русский'
    title = 'Чемпионат по портированию и оптимизации программного обеспечения RISC-V'
    weight = 3
    [languages.ru.params]
      #registration_url = 'https://www.wenjuan.com/s/UZBZJveQl0k/'
      [[languages.ru.params.banners]]
        text = 'Срок регистрации и подачи заявок на этот чемпионат продлен до 29 февраля 2024 года.'
        link = 'https://rvspoc.org/02/'
      [[languages.ru.params.banners]]
        text = '本次锦标赛的获奖结果已公布，公示期为 2024 年 4 月 3 日 —— 2024 年 4 月 10 日。'
        link = 'https://rvspoc.org/05/'
  [languages.ja]
    contentDir = 'content/ja'
    disabled = false
    languageCode = 'ja-JP'
    languageDirection = 'ltr'
    languageName = '日本語'
    title = 'RISC-V ソフトウェアの移植と最適化チャンピオンシップ'
    weight = 4
    hasCJKLanguage = true
    summaryLength = 230
    [languages.ja.params]
      #registration_url = 'https://www.wenjuan.com/s/UZBZJveQl0k/'
      [[languages.ja.params.banners]]
        text = 'チャンピオンシップの登録および提出期限は2024年2月29日まで延長されます.'
        link = 'https://rvspoc.org/02/'
      [[languages.ja.params.banners]]
        text = '本次锦标赛的获奖结果已公布，公示期为 2024 年 4 月 3 日 —— 2024 年 4 月 10 日。'
        link = 'https://rvspoc.org/05/'
  [languages.ko]
    contentDir = 'content/ko'
    disabled = false
    languageCode = 'ko-KR'
    languageDirection = 'ltr'
    languageName = '한국어'
    title = 'RISC-V 소프트웨어포팅및최적화챔피언십'
    weight = 5
    hasCJKLanguage = true
    summaryLength = 230
    [languages.ko.params]
      #registration_url = 'https://www.wenjuan.com/s/UZBZJveQl0k/'
      [[languages.ko.params.banners]]
        text = '챔피언십 등록 및 제출 기한은 2024년 2월 29일까지 연장됩니다.'
        link = 'https://rvspoc.org/02/'
      [[languages.ko.params.banners]]
        text = '本次锦标赛的获奖结果已公布，公示期为 2024 年 4 月 3 日 —— 2024 年 4 月 10 日。'
        link = 'https://rvspoc.org/05/'
